# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afaf6fa031312d6ff97078f4f0f5465ff67991354a77d79f64d648c7ba839321e65716ef27add68468b59b421b5b09a6770abe68f8cf7d717710471f60db1cd5

test:
  secret_key_base: 752e8ec99cb0a384bdb4622b70a90d981edf65c20710e65988e69431329421cd320196da59bb9214edcea66991cd04a6e8143c7579186264a6773457b68cb5a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
